[package]
name = "push-notification"
version = "0.1.0"
authors = ["mdeveloper66 <m.developer66@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ws = "0.9.1"
